#数据接口
server:
  port: 8088

# netty接口
netty:
  port: 8089
spring:
  datasource:
    url: 
    driverClassName: 
    username: 
    password: 

  application:
    name: talk_later



#日志文件信息
#logging:
#  level:
#    org.springframework.web: INFO,CONSOLE
#  config: classpath:logback-spring.xml