server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/talk_later?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  application:
    name: talk_later



#日志文件信息
#logging:
#  level:
#    org.springframework.web: INFO,CONSOLE
#  config: classpath:logback-spring.xml