#数据接口
server:
  port: 8088

# netty接口
netty:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/talk_later?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  application:
    name: talk_later

#mybatis:
#  mapper-locations: classpath:mapper/*.xml #指定xml配置文件的位置

aliyun:
  oss:
    endpoint: "oss-cn-guangzhou.aliyuncs.com"
    accessKeyId: "LTAI4GHHHS9YKUyvqcLRCYcE"
    accessKeySecret: "s3mPePeMcV4aU3SX1RvxHzI3ki4SsR"
    bucketName: "talk-later-file"

qrcode:
  path: "qrCode/"







