#数据接口
server:
  port: 8080

# netty接口
netty:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/talk_later?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  application:
    name: talk_later

mybatis:
  mapper-locations: classpath:mapper/*.xml #指定xml配置文件的位置

#日志文件信息，部署上线再启用
#logging:
#  level:
#    org.springframework.web: INFO
#  config: classpath:logback-spring.xml





