#数据接口
server:
  port: 8088

# netty接口
netty:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://47.106.228.148:3306/talk_later?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: guest
    password: 1234

  application:
    name: talk_later



#日志文件信息
#logging:
#  level:
#    org.springframework.web: INFO,CONSOLE
#  config: classpath:logback-spring.xml